### ISSUE TITLE
[QA] Goerli | UI-Animations: Actions Not Matching in Prod

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1295]
### **Explorer Alpha build version:**
v0.4.0

### **Issue Description:**
In the Goerli scene UI-Animations (72,-1), several interactive elements do not function as expected compared to the production environment. The following issues have been identified:

- 'Pop-up': No action occurs when clicking the box in both production and EA.
- 'Sprite Animation': The character does not move.
- 'Spinner' and 'Spinner Ray': The spinners do not rotate.
- 'Counter': The counter does not increment when clicking the box.
- 'Progress Bar': The progress bar does not increase when clicking the box.
- 'Complex Example': Neither the progress bar nor the counter increases when clicking the box.

### **Steps to reproduce:**

1. /goto goerli
2. Navigate to the UI-Animations scene (72,-1)
3. Interact with each of the following elements:
- 'Pop-up'
- 'Sprite Animation'
- 'Spinner' and 'Spinner Ray'
- 'Counter'
- 'Progress Bar'
- 'Complex Example'

### **Expected behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/4f3f50fc-796f-4b2e-ae8f-8b4903a20543

### **Current behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/c900e203-779d-400b-a259-c1abd563ebb7

#### ** 🖥️ Platform:**

- Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
- Macbook M1 Pro Sonoma 14.5

**Comment by m3taphysics** [comment]
Fixed as of latest main.

**Comment by nearnshaw** [comment]
With a commit from today this is working a LOT better, but still not all.

The first 3 boxes don't work (pop-up, buttons, card flip), the others do work just fine :D

In the last one (complex example) it mostly works, except that the number inside the progress bar is only showing one digit, it goes back to 0 every time you pass 9.
