### ISSUE TITLE
[QA] Missing pieces of road in some locations

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#2419]
### **Explorer Alpha build versions:**
Not version specific

### **Issue Description:**

In certain locations (this example is in `15,-135` there are roads missing on the surrounding areas, but the map shows as if the roads are present. The roads missing are different from the ones that are currently working on Alpha, since this issue is also present in the old explorer version. The evidence shown in this ticket comes from a report of the user and is marking the places in which the roads are being cut by some other scenes.

#### **Evidence:**
![image](https://github.com/user-attachments/assets/a5cdce03-bffa-4ad2-bb57-4fe104f8f4d8)

**Comment by Kaze-No-Kai** [comment]
another user:
![Screenshot 2024-10-29 180010](https://github.com/user-attachments/assets/39bb202c-2343-4aa5-8ad3-48efa8ba8fbc)

**Comment by Kaze-No-Kai** [comment]
Another example of missing roads: 58,-150
<img width="1120" alt="Screenshot_2024-11-13_at_9 17 53_AM" src="https://github.com/user-attachments/assets/4468dcfb-fa92-45e9-8a9c-c064801a38fa">

**Comment by ai47patos** [comment]
Hi, as this seems related to fixed issues #2578 and #2882 
Could it be fixed in the same way as those issues?

**Comment by anicalbano** [comment]
Still happening on latest version (v0.52.0)

![Image](https://github.com/user-attachments/assets/da56155a-1c46-42c5-88a0-3011d5a80ce9)

![Image](https://github.com/user-attachments/assets/f7ae6aea-07ef-4fae-9299-dc7ea0c544c8)

**Comment by sandrade-dcl** [comment]
Roads updated! ✔ 
- 7,-137 to 7,-133 (except for 7,-134)
- 16,-133
- (24,-150), (26,-150), (27,-150), (30,-150), (31,-150)
- (42,-150), (44 to 47,-150)

I cannot update these another ones because I don't know how is the design of the streets in that part of the map ❌ 
- (45,-117) , (42,-117)
- (41,-115), (41,-113), (41,-112)
- (43,-112)
- (32,-115)
- (20,-112)
- (30,-117), (28,-117)
- (52,-115), (52,-116)

We should pass them to someone in the content team to update them according to the correct design of Genesis City.
