### ISSUE TITLE
[QA] Minigames | Progress Not Consistently Recorded

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2746]
### **Build version:**

- **v0.40.0**
- **v0.46.0**

### **Issue Description:**
Progress in certain minigames is intermittently not recorded, even after the user completes the required tasks. This issue has been observed across multiple minigames (e.g., Mosaic Mania, Memory Grid, Salad Slash). Players report that despite reaching the target score, their progress fails to register in the Daily Quest UI, preventing the missions from being marked as complete. Restarting the Explorer temporarily resolves the issue, but it frequently reoccurs.

### **STR:** 

1. Enter any of the assigned daily mission minigames.
2. Complete the mission.
3. Exit the minigame.
4. Check the Daily Quest UI to see if the mission is marked as complete.
5. If the mission is not marked as complete, restart the Explorer and check again.

### ❌ Actual Result
The Daily Quest UI does not mark the mission as complete, despite the user reaching the required score.

### ✅ Expected Result
The Daily Quest UI should reliably mark the mission as complete upon achieving the required score, without needing to restart the Explorer.

### **Repro Index:**
3/10 

### **Evidence & LOGS:**

LOGS: [Player.zip](https://github.com/user-attachments/files/17683975/Player.zip)

![image (1)](https://github.com/user-attachments/assets/e54f9e78-0a60-499c-8c56-a36a1801dd8e)

https://github.com/user-attachments/assets/9bceadfb-23da-4be9-abd7-577a84066b72

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by ZomDCL** [comment]
I have been able to repeat this on this recent (today's) quests for mini-games.  I had Color Pop, Minesweeper, and Liquid Labyrinth ... none of them counted my first time reaching the requirements for the daily quest to update.

Minesweeper and Color Pop took 2-3 trys a piece to get them to count my progress on quest.  I have played Liquid Labyrinth 7 times with no daily quest update yet ... even played passed the requirement incase it was a display error.

Toria (a local friend of mine) could not get Liquid Labyrinth to update her daily quests either.  I, also, chatted with two other players (maybe new) while trying to get updates and they stated having problems getting dailys to update on mini-games.

**Comment by Vitsky4079** [comment]
Another user logs:

[Playerlog.zip](https://github.com/user-attachments/files/17688509/Playerlog.zip)
[mainlog.zip](https://github.com/user-attachments/files/17688510/mainlog.zip)

**Comment by DafGreco** [comment]
Hey team ! I was able to reproduce this issue today with salad slash. I need to complete missions and one of them was to reach to the 30000 points on salad slash. Seems that the quest is not tracking progress. 

https://github.com/user-attachments/assets/9cf43f20-b244-46b5-9876-889a6cb08525

**Comment by Vitsky4079** [comment]
I've got another user with this issue, unfortunately, he was not able to record the whole process as it got fixed for him after restarting the client.

![image](https://github.com/user-attachments/assets/dde66605-9bb5-4666-a3fa-3d9b45701b71)

**Comment by Vitsky4079** [comment]
Another example: https://drive.google.com/file/d/1-WVKV7cBR6jQkjv_vycyYe9Zb5TIY2P9/view?usp=sharing
![image](https://github.com/user-attachments/assets/49155b13-d4ea-4648-8f4e-e894a31bb51b)

**Comment by WarGames1983** [comment]
Me too, on the Tower of Hanoi Level 5 Quest, completion is not being recognised. I have restarted the client multiple times and played multiple times still with no success.

![image](https://github.com/user-attachments/assets/9ecaf053-15d1-47df-8ac2-bdc324a2987a)

**Comment by m3taphysics** [comment]
Fixed with https://github.com/decentraland/unity-explorer/issues/2686

**Comment by WarGames1983** [comment]
Hi, I'm still experiencing this issues, it's been 7 days now, and I haven't been able to complete any daily rewards.

**Comment by WarGames1983** [comment]
> Closing the ticket for version v0.50.0 after reviewing on both Mac and Windows. The Liquid Labyrinth issue has been resolved, and mission progress is functioning correctly. We’ll reopen if the issue reoccurs.

Hi, I retested this issue with DCL Client v0.50.0 on Mac x86 and this issue is still unresolved (refer screenshot from today). Could you please reopen the ticket to investigate further.

<img width="1437" alt="Screenshot 2025-01-15 at 12 05 52 AM" src="https://github.com/user-attachments/assets/b5501dc2-e899-4c24-bc74-810a25c972f1" />
